@extends('layouts.app')

@section('title', 'Health Library - Maruti Hospital')

@section('content')
  <section class="page-hero"><div class="container"><div class="breadcrumb"><a href="{{ route('home') }}">Home</a><span class="separator">/</span><span style="color:white">Health Library</span></div><h1>Health Library</h1><p>Practical health guidance and trusted advice from the Maruti Hospital team.</p></div></section>
  <section class="library"><div class="container"><div class="library-head"><div><span class="section-badge">Patient education</span><h2 class="section-title">Helpful information for healthier choices</h2></div><a class="btn btn-outline" href="{{ route('health-library') }}">All articles</a></div>
    @if($topics->isNotEmpty())<nav class="topic-list" aria-label="Health topics">@foreach($topics as $topic)<a href="{{ route('health-library', ['topic' => $topic]) }}" class="{{ request('topic') === $topic ? 'active' : '' }}">{{ $topic }}</a>@endforeach</nav>@endif
    <div class="article-grid">@forelse($articles as $article)<article class="article-card"><a class="article-image" href="{{ route('health-article', $article) }}" @if($article->image) style="background-image:url('{{ asset($article->image) }}')" @endif aria-label="Read {{ $article->title }}"></a><div class="article-body"><span class="article-topic">{{ $article->tag ?: 'Health guide' }}</span><h2><a href="{{ route('health-article', $article) }}">{{ $article->title }}</a></h2><p>{{ str(strip_tags($article->content))->limit(150) }}</p><div class="article-meta">{{ $article->published_at?->format('d M Y') }} · {{ $article->author }}</div><a class="article-read" href="{{ route('health-article', $article) }}">Read article <span>→</span></a></div></article>@empty<div class="library-empty"><h2>No articles found</h2><p>New health guides will appear here soon.</p></div>@endforelse</div>{{ $articles->links() }}</div></section>
  <style>.library{padding:80px 0;background:#f5f8fc}.library-head{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:24px}.library-head .section-title{max-width:650px;margin-top:12px}.topic-list{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:32px}.topic-list a{padding:8px 13px;border:1px solid #dce6f3;border-radius:999px;color:var(--text-secondary);font-size:13px;text-decoration:none}.topic-list a:hover,.topic-list a.active{background:var(--primary);border-color:var(--primary);color:#fff}.article-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.article-card{overflow:hidden;background:#fff;border:1px solid #EDF2F7;border-radius:16px;box-shadow:0 8px 22px rgba(21,62,110,.06)}.article-image{display:block;height:190px;background:#D1E0EC center/cover no-repeat}.article-image:not([style]){background-image:linear-gradient(135deg,#123B5D,#159A9C)}.article-body{padding:22px}.article-topic{color:var(--primary);font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.article-card h2{margin:10px 0;font-size:19px;line-height:1.35}.article-card h2 a{color:var(--text);text-decoration:none}.article-card p{color:var(--text-secondary);font-size:14px;line-height:1.65}.article-meta{margin-top:16px;color:#7588a0;font-size:12px}.article-read{display:inline-flex;margin-top:16px;gap:8px;color:var(--primary);font-size:13px;font-weight:700;text-decoration:none}.article-read span{font-size:18px;line-height:.8}.library-empty{grid-column:1/-1;padding:52px;text-align:center;background:#fff;border-radius:16px;color:var(--text-secondary)}@media(max-width:900px){.article-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.library{padding:60px 0}.library-head{align-items:start;flex-direction:column}.article-grid{grid-template-columns:1fr}}</style>
@endsection
