@extends('layouts.app')
@section('meta_description', 'Maruti Multispeciality Hospital in Bhopal offers 24/7 emergency care, advanced diagnostics, and specialist consultations. NABH accredited.')

@section('content')
    @include('partials.home.hero')
    @include('partials.home.quick-access')
    @include('partials.home.about')
    @include('partials.home.departments')
    @include('partials.home.why-choose-us')
    @include('partials.home.doctors')
    @include('partials.home.services')
    @include('partials.home.facilities')
    @include('partials.home.testimonials')
    @include('partials.home.blog')
    @include('partials.home.appointment-cta')
@endsection
