@extends('admin.layouts.app')
@section('title', 'Appointment request | Maruti Hospital Admin')
@section('page-title', 'Appointment request')
@section('breadcrumb', 'Maruti Hospital Admin | Appointments | Request #' . $appointment->id)
@section('content')
  <div class="page-head"><div><h2>{{ $appointment->patient_name }}</h2><p>Submitted {{ $appointment->created_at->format('d M Y, h:i A') }}</p></div><a class="button button-muted" href="{{ route('admin.appointments') }}">Back to appointments</a></div>
  @if(session('success'))<div class="notice">{{ session('success') }}</div>@endif
  <div class="detail-grid"><section class="panel"><h2>Patient details</h2><div class="detail-item"><label>Phone</label><strong>{{ $appointment->phone }}</strong></div><div class="detail-item"><label>Email</label><strong>{{ $appointment->email ?: 'Not provided' }}</strong></div><div class="detail-item"><label>Age / gender</label><strong>{{ $appointment->age ?: 'Not provided' }}{{ $appointment->gender ? ' / ' . ucfirst($appointment->gender) : '' }}</strong></div></section><section class="panel"><h2>Requested appointment</h2><div class="detail-item"><label>Department</label><strong>{{ $appointment->department }}</strong></div><div class="detail-item"><label>Preferred doctor</label><strong>{{ $appointment->preferred_doctor ?: 'Any available doctor' }}</strong></div><div class="detail-item"><label>Preferred time</label><strong>{{ $appointment->preferred_date->format('d M Y') }} | {{ $appointment->time_slot }}</strong></div></section></div>
  <section class="panel" style="margin-top:14px"><h2>Request & follow-up</h2><div class="detail-item"><label>Reason for visit / symptoms</label><strong>{{ $appointment->symptoms ?: 'Not provided' }}</strong></div><form method="post" action="{{ route('admin.appointments.update', $appointment) }}">@csrf @method('PATCH')<label for="status">Appointment status</label><select class="form-control" id="status" name="status">@foreach(['pending','confirmed','completed','cancelled'] as $status)<option value="{{ $status }}" @selected($appointment->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select><label for="admin_notes" style="display:block;margin-top:14px">Internal follow-up notes</label><textarea class="form-control notes" id="admin_notes" name="admin_notes" placeholder="Add call outcome, confirmation details, or internal notes. Do not store clinical records here.">{{ old('admin_notes', $appointment->admin_notes) }}</textarea><button class="button">Save appointment update</button></form></section>
@endsection
